### ISSUE TITLE
Date/time completion?

### ISSUE THREAD

**Issue by JamieGruener** [mattdodge/nyt-crossword-stats#1]
First, thank you for doing this! I've been wondering about my stats, especially whether I've been getting any faster or competing more frequently, and the stats page is so...weak. With the raw data, I'll be able to do all sorts of fun things.

Here's my question. In the output, there's no difference between a puzzle I completed the day it was released and a puzzle I completed days later. While NYT does track my longest streak and my current streak, I'd still like to know my average streak length as well as the rate of completion of puzzles on the day they were released. Is this data available?

Thanks,
--Jamie

**Comment by mattdodge** [comment]
This is a good question, the short answer is "kind of."

I pretty much had to reverse engineer these APIs so there are a handful of fields that are not documented that I'm not sure about. I was looking to find pretty much the exact same thing you were - does a given puzzle count towards a "streak" or not. 

Here is an example result of a puzzle (July 2, 2018) that I solved without hints but well after the day had passed (solved on Oct 27, 2018):
```json
"results": {
  "board": [...],
  "eligible": false,
  "firstOpened": 1540661673,
  "firstSolved": 1540662019,
  "id": "86925616-15376",
  "isPuzzleInfoRead": false,
  "lastUpdateTime": 1540662020,
  "solved": true,
  "completed": true,
  "timeElapsed": 346,
  "epoch": 1540661676
}
```

And then here is a puzzle (April 23, 2019) that I solved without hints but on the day, thus counting towards my streak:
```json
"results": {
  "board": [...],
  "eligible": false,
  "firstOpened": 1556055012,
  "firstSolved": 1556055784,
  "id": "86925616-16592",
  "isPuzzleInfoRead": false,
  "lastUpdateTime": 1556055786,
  "solved": true,
  "completed": true,
  "timeElapsed": 730,
  "epoch": 1556055015
}
```

Originally, I had thought that the `solved`, `completed`, or `eligible` fields might represent whether a puzzle counted for a streak or not, but that doesn't seem to be the case since they are the same in both of those puzzles.

So unfortunately I think we're left with looking at the `firstSolved` timestamp and then comparing to the puzzle's date. I also can't find a consistent answer (or one that I can reproduce) as to when the cutoff is for when a puzzle is no longer eligible for a streak. 

It's not as clean as the boolean fields and I wouldn't be 100% confident in the logic but I do think adding a feature to this repo to add a `streakEligible` field seems like a good idea. If that logic evolves over time as I understand more and more about the API then so be it.

**Comment by JamieGruener** [comment]
My guess is that `firstSolved` is actually just the solved date. It would be interesting to compare the output of a puzzle that was completely filled in but wrong. I’d expect that `firstSolved` would update and stop updating once all the squares were correct and you got the happy music. I’d bet that `solved` is `false` until all squares are correct.

From experience, and from what I’ve read, puzzles count towards a streak if they are solved correctly by midnight PST/PDT. At one point that was midnight EST/EDT, but it switched to accommodate those on the left coast, and inadvertently helping east coast night owls, like myself.

The logic for “streak eligible” would be a puzzle where `solved` is `true` and `firstSolved` <= midnight of puzzle date in PST/PDT.

(It’s also possible that it’s `lastUpdateTime` instead of `firstSolved` but those are barely different in your examples.)

Thanks again!

--Jamie

**Comment by mattdodge** [comment]
You're right, `firstSolved` is the timestamp of when the puzzle is "solved," which means all squares filled in and all correct. When that happens `firstSolved`, `solved`, and `completed` are all set.

When I wrote this I suspected that `completed` might have meant what you were describing, all squares filled in but not correct. However, that didn't seem to be the case. I couldn't get a puzzle into a  state where `completed` and `solved` were ever different from one another.

Your logic for streak eligible is correct, with a couple of additional items needed:
- `solved` is `true`
- `firstSolved` is earlier than Midnight PST of the following day
- `firstChecked` is not set - this field is set when you "check" that something is correct
- `firstRevealed` is not set - this field is set when you "reveal" something in the puzzle

I'll update accordingly and add a new `streakEligible` field in the next few days

**Comment by JamieGruener** [comment]
Excellent! And thank you for understanding what I meant and not what I wrote. I look forward to the update.

**Comment by angiesassi** [comment]
Thank you so much for making this code! I have one of the same original questions as @JamieGruener. Is it possible to update the code so that the solved date (`firstSolved`) is included as an additional variable in the CSV file? I tried editing the code on my own to add this feature but I ended up with a column of NA's.
